# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ''

# Title of the Site
title: Magnus Grande
# Description of the Site
description: An ever growing e-portfolio
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: Portfolio
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://upload.wikimedia.org/wikipedia/commons/3/34/2016-11-13_02_Kjeungskj%C3%A6r_Lighthouse%2C_S%C3%B8r-Tr%C3%B8ndelag%2C_Norway.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: magnusgrande@gmail.com
facebook_username:
twitter_username:
instagram_username:
linkedin_username: magnus-grande-59b5a3126
github_username: magnusgrande
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: /

# Disqus
disqus-shortname: /

# Name of the Author
author-name: Magnus Grande
# URL for the Image of the Author
author-image: https://media.discordapp.net/attachments/422910717419585555/1294337597102882848/mag.png?ex=670aa552&is=670953d2&hm=9b63d00d793b37a9f851b4c7a650052f285234c2afe303429085123b142a895d&=&format=webp&quality=lossless&width=437&height=437
# 60 Words About the Author
author-about: I am a computer science student at NTNU in Ålesund, Norway. My main interests beyond my line of study are disc golf and floorball. In this portfolio you will find any and everything one might want to know about me, my life and my future plans.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/magnusgrande

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
