# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ''

# Title of the Site
title: Magnus Grande
# Description of the Site
description: Getting better at this with every commit
# URL of Image of the Site
site-image: /assets/images/site.png
# Keywords of the Site
site-keywords: Portfolio
# URL for the Image of custom Favicon
favicon-url: /assets/images/favicon.ico

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://upload.wikimedia.org/wikipedia/commons/3/34/2016-11-13_02_Kjeungskj%C3%A6r_Lighthouse%2C_S%C3%B8r-Tr%C3%B8ndelag%2C_Norway.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: magnugra@stud.ntnu.no
linkedin_username: magnus-grande-59b5a3126
github_username: magnusgrande

# Google Analytics
google-analytics: /

# Disqus
disqus-shortname: /

# Name of the Author
author-name: Magnus Grande
# URL for the Image of the Author
author-image: /assets/images/mag.png
# About section on the front page
author-about: I am a computer science student at NTNU in Ålesund, Norway.<br> My main interests beyond my line of study are disc golf (since 2019) and floorball (since 2014).<br> This Portfolio should, ideally, have everything you need to know about me, my academic progress and the projects I'm working on.
# URL to the Author's Profile (i.e., GitHub, Twitter, StackOverflow, etc.)
author-url: https://github.com/magnusgrande

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Collections adds recognition of the projects directory
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
